# Generated by Django 3.0.7 on 2020-06-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20200621_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(default='Sun Jun 21 09:10:54 2020'),
        ),
    ]
