# Generated by Django 3.0.7 on 2020-06-20 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START_TIME', models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 3, 50, 979801))),
                ('END_TIME', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='START_TIME',
        ),
    ]
