# Generated by Django 3.0.7 on 2020-06-20 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20200621_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.Members'),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 0, 35, 17, 294629)),
        ),
    ]
