# Generated by Django 3.0.7 on 2020-06-21 01:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20200621_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='END_TIME',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='START_TIME',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 7, 9, 15, 597220)),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='Api.Members'),
        ),
    ]
